"""
6_Appointments.py
------------------
Appointment booking system for the RPM platform.

Doctor can:
  - Book appointments for patients (especially after severe/critical alerts)
  - View all upcoming and past appointments
  - Cancel or complete appointments
  - Add doctor notes after the appointment

Patient can:
  - See all their upcoming appointments with date, time, location
  - Get notified when a new appointment is booked
  - Add patient notes / confirm attendance
  - See appointment history
"""

import streamlit as st
from datetime import datetime, date, timedelta
import io

from app.core.security import SessionManager
from app.database.repositories.appointment_repository import AppointmentRepository
from app.database.repositories.message_repository import MessageRepository
from app.database.repositories.patient_repository import PatientRepository
from app.database.repositories.doctor_schedule_repository import DoctorScheduleRepository
from app.utils.custom_css import apply_theme, profile_widget, notification_bell, page_header

# ── Session ──────────────────────────────────────────────────────
user = SessionManager.get_current_user()
if not user:
    st.set_page_config(page_title="Appointments", page_icon="📅", layout="wide")
    st.warning("Please log in first.")
    st.stop()

role = user["role"]
appt_repo = AppointmentRepository()
msg_repo = MessageRepository()
patient_repo = PatientRepository()
doctor_schedule_repo = DoctorScheduleRepository()

# ── Page title with upcoming count ───────────────────────────────
if role == "patient":
    upcoming = appt_repo.get_for_patient(user["id"], upcoming_only=True)
elif role == "doctor":
    upcoming = appt_repo.get_for_doctor(user["id"], upcoming_only=True)
else:
    upcoming = []

badge = f" ({len(upcoming)} upcoming)" if upcoming else ""
st.set_page_config(page_title=f"Appointments{badge}", page_icon="📅", layout="wide")
apply_theme()
profile_widget(user)
notification_bell(user)

st.markdown(page_header("📅", "Appointments", f"Manage and track your appointments.{badge}"), unsafe_allow_html=True)

_STATUS_COLORS = {
    "scheduled":  ("🔵", "#E7F0F7"),
    "completed":  ("✅", "#E7F4EF"),
    "cancelled":  ("❌", "#FBE9E7"),
    "rescheduled":("🔄", "#FBF3E4"),
}

_SEVERITY_ICONS = {
    "normal":   "🟢", "mild":     "🟡",
    "moderate": "🟠", "severe":   "🔴", "critical": "🚨",
}

def format_date(d):
    if isinstance(d, date):
        return d.strftime("%A, %d %B %Y")
    return str(d)

def format_time(t):
    if hasattr(t, "strftime"):
        return t.strftime("%I:%M %p")
    if hasattr(t, "seconds"):
        total = int(t.total_seconds())
        h, m = divmod(total // 60, 60)
        return f"{h:02d}:{m:02d}"
    return str(t)


def generate_appointment_text(appt, patient_name: str) -> str:
    sev_icon = _SEVERITY_ICONS.get(appt.severity_level, "🔵")
    lines = [
        "=" * 50,
        "  REMOTE PATIENT MONITORING SYSTEM",
        "  Appointment Details",
        "=" * 50,
        "",
        f"  Patient:     {patient_name}",
        f"  Doctor:      Dr. {appt.doctor_name}",
        "",
        f"  📆 Date:      {format_date(appt.appointment_date)}",
        f"  ⏰ Time:      {format_time(appt.appointment_time)}",
        f"  📍 Location:  {appt.location}",
        f"  {sev_icon} Urgency:   {appt.severity_level.upper()}",
        f"  📋 Status:    {appt.status.upper()}",
        "",
    ]
    if appt.reason:
        lines += ["  📝 REASON:", f"  {appt.reason}", ""]
    if appt.doctor_notes:
        lines += ["  📋 DOCTOR'S NOTES:", f"  {appt.doctor_notes}", ""]
    if appt.patient_notes:
        lines += ["  📝 YOUR NOTES:", f"  {appt.patient_notes}", ""]
    lines += [
        "=" * 50,
        "  Generated by RPM System",
        f"  {datetime.now().strftime('%d %B %Y, %H:%M')}",
        "=" * 50,
    ]
    return "\n".join(lines)


def generate_appointment_html(appt, patient_name: str) -> str:
    sev_icon = _SEVERITY_ICONS.get(appt.severity_level, "🔵")
    return f"""
    <div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;padding:20px;">
        <div style="text-align:center;border-bottom:3px solid #0E7A5C;padding-bottom:12px;margin-bottom:16px;">
            <h2 style="color:#0E7A5C;margin:0;">Remote Patient Monitoring System</h2>
            <p style="color:#666;margin:4px 0 0;">Appointment Details</p>
        </div>
        <table style="width:100%;border-collapse:collapse;font-size:14px;">
            <tr><td style="padding:8px;font-weight:bold;color:#555;">Patient</td><td style="padding:8px;">{patient_name}</td></tr>
            <tr><td style="padding:8px;font-weight:bold;color:#555;">Doctor</td><td style="padding:8px;">Dr. {appt.doctor_name}</td></tr>
            <tr><td style="padding:8px;font-weight:bold;color:#555;">📆 Date</td><td style="padding:8px;font-weight:600;">{format_date(appt.appointment_date)}</td></tr>
            <tr><td style="padding:8px;font-weight:bold;color:#555;">⏰ Time</td><td style="padding:8px;font-weight:600;">{format_time(appt.appointment_time)}</td></tr>
            <tr><td style="padding:8px;font-weight:bold;color:#555;">📍 Location</td><td style="padding:8px;">{appt.location}</td></tr>
            <tr><td style="padding:8px;font-weight:bold;color:#555;">{sev_icon} Urgency</td><td style="padding:8px;">{appt.severity_level.upper()}</td></tr>
            <tr><td style="padding:8px;font-weight:bold;color:#555;">📋 Status</td><td style="padding:8px;">{appt.status.upper()}</td></tr>
        </table>
        {"<div style='background:#E7F4EF;border-left:4px solid #0E7A5C;padding:12px;margin:12px 0;border-radius:4px;'><strong>📝 Reason:</strong><br>" + appt.reason + "</div>" if appt.reason else ""}
        {"<div style='background:#E7F0F7;border-left:4px solid #2A6A9B;padding:12px;margin:12px 0;border-radius:4px;'><strong>📋 Doctor's Notes:</strong><br>" + appt.doctor_notes + "</div>" if appt.doctor_notes else ""}
        <div style="text-align:center;margin-top:20px;padding-top:12px;border-top:1px solid #ddd;color:#999;font-size:11px;">
            Generated by RPM System — {datetime.now().strftime('%d %B %Y, %H:%M')}
        </div>
    </div>
    """


# ================================================================
# DOCTOR VIEW
# ================================================================
if role == "doctor":
    book_tab, upcoming_tab, history_tab = st.tabs([
        "📋 Book Appointment", "📅 Upcoming", "🗂️ History"
    ])

    # ── Get patients ─────────────────────────────────────────────
    from app.services.doctor_service import DoctorService
    doctor_service = DoctorService()
    patients = doctor_service.get_assigned_patients(user["id"])
    patient_map = {
        (p.full_name or f"Patient #{p.user_id}"): p.user_id
        for p in patients
    }

    # ── TAB 1: Book Appointment ──────────────────────────────────
    with book_tab:
        st.subheader("📋 Book a New Appointment")
        st.caption("Book a face-to-face appointment for a patient, especially after severe or critical alerts.")

        if not patients:
            st.info("No patients assigned to you yet.")
        else:
            # Check doctor availability for default appointment date
            from app.database.repositories.doctor_schedule_repository import DAY_NAMES
            default_appt_date = date.today() + timedelta(days=3)
            day_of_week = default_appt_date.weekday()
            doctor_schedule = doctor_schedule_repo.get_schedule_for_day(user["id"], day_of_week)
            if not doctor_schedule:
                st.warning(f"⚠️ You don't have a schedule set for {default_appt_date.strftime('%A')}s. "
                          "Go to 'Profile' to set your availability schedule.")

            with st.form("book_appt_form", clear_on_submit=True):
                col1, col2 = st.columns(2)
                with col1:
                    selected_patient = st.selectbox(
                        "Select Patient", list(patient_map.keys())
                    )
                    appt_date = st.date_input(
                        "Appointment Date",
                        min_value=date.today() + timedelta(days=1),
                        value=date.today() + timedelta(days=3),
                    )
                    location = st.text_input(
                        "Location / Clinic",
                        value="Hospital Clinic",
                        placeholder="e.g. Room 12, Outpatient Clinic, UENR Health Centre"
                    )

                with col2:
                    appt_time = st.time_input(
                        "Appointment Time",
                        value=datetime.strptime("09:00", "%H:%M").time(),
                    )
                    severity = st.selectbox(
                        "Reason for Urgency",
                        ["moderate", "severe", "critical", "routine", "follow-up"],
                        format_func=lambda x: {
                            "critical":  "🚨 Critical — Emergency follow-up",
                            "severe":    "🔴 Severe — Urgent review needed",
                            "moderate":  "🟠 Moderate — Soon review",
                            "routine":   "🟢 Routine check-up",
                            "follow-up": "🔵 Follow-up appointment",
                        }.get(x, x)
                    )
                    notify = st.checkbox("Send notification message to patient", value=True)

                reason = st.text_area(
                    "Reason / Notes for Patient",
                    placeholder="e.g. Follow-up after high blood pressure reading. Please bring your medication list.",
                    help="This message will be sent to the patient."
                )

                if st.form_submit_button("📅 Book Appointment", width="stretch"):
                    if not reason.strip():
                        st.error("Please enter a reason for the appointment.")
                    else:
                        # Validate doctor availability for selected date
                        selected_day_of_week = appt_date.weekday()
                        selected_schedule = doctor_schedule_repo.get_schedule_for_day(user["id"], selected_day_of_week)
                        if not selected_schedule:
                            st.error(f"⚠️ You are not available on {appt_date.strftime('%A')}s. "
                                    "Go to 'Profile' to set your availability schedule.")
                        else:
                            patient_uid = patient_map[selected_patient]

                            # Book appointment
                            appt_id = appt_repo.create(
                                doctor_id=user["id"],
                                patient_id=patient_uid,
                                appointment_date=appt_date,
                                appointment_time=appt_time,
                                location=location,
                                reason=reason.strip(),
                                severity_level=severity,
                            )

                            # Notify patient via message
                            if notify:
                                sev_icon = _SEVERITY_ICONS.get(severity, "🔵")
                                msg_body = (
                                    f"📅 APPOINTMENT BOOKED\n"
                                    f"{'=' * 45}\n"
                                    f"Dear {selected_patient},\n\n"
                                    f"Dr. {user['full_name']} has booked an appointment for you.\n\n"
                                    f"📆 DATE:      {format_date(appt_date)}\n"
                                    f"⏰ TIME:      {format_time(appt_time)}\n"
                                    f"📍 LOCATION:  {location}\n"
                                    f"{sev_icon} URGENCY:   {severity.upper()}\n\n"
                                    f"📋 REASON:\n{reason.strip()}\n\n"
                                    f"{'=' * 45}\n"
                                    f"Please make sure you attend this appointment.\n"
                                    f"If you cannot make it, reply to this message.\n\n"
                                    f"— Dr. {user['full_name']}"
                                )
                                msg_repo.send(
                                    sender_id=user["id"],
                                    receiver_id=patient_uid,
                                    subject=f"📅 Appointment Booked — {format_date(appt_date)} at {format_time(appt_time)}",
                                    body=msg_body,
                                )

                                # Send email notification
                                from app.services.email_service import EmailService
                                from app.database.repositories.user_repository import UserRepository
                                email_svc = EmailService()
                                patient_user = UserRepository().get_by_id(patient_uid)
                                if patient_user and patient_user.email:
                                    email_svc.send_appointment_notification(
                                        to_email=patient_user.email,
                                        patient_name=selected_patient,
                                        doctor_name=user["full_name"],
                                        appointment_date=format_date(appt_date),
                                        appointment_time=format_time(appt_time),
                                        location=location,
                                        notification_type="scheduled",
                                    )

                            st.success(f"✅ Appointment booked for {selected_patient} on {format_date(appt_date)} at {format_time(appt_time)}!")
                            if notify:
                                st.info(f"📨 Notification sent to {selected_patient}.")

    # ── TAB 2: Upcoming ──────────────────────────────────────────
    with upcoming_tab:
        st.subheader("📅 Upcoming Appointments")
        upcoming_appts = appt_repo.get_for_doctor(user["id"], upcoming_only=True)

        if not upcoming_appts:
            st.info("No upcoming appointments.")
        else:
            for appt in upcoming_appts:
                sev_icon = _SEVERITY_ICONS.get(appt.severity_level, "🔵")
                status_icon, _ = _STATUS_COLORS.get(appt.status, ("🔵", "#fff"))

                with st.container(border=True):
                    col1, col2, col3 = st.columns([4, 1, 1])
                    with col1:
                        st.markdown(f"### {sev_icon} {appt.patient_name}")
                        st.write(f"📆 **{format_date(appt.appointment_date)}** at ⏰ **{format_time(appt.appointment_time)}**")
                        st.write(f"📍 {appt.location}")
                        if appt.reason:
                            st.caption(f"Reason: {appt.reason}")
                        st.caption(f"Status: {status_icon} {appt.status.title()}")
                    with col2:
                        if appt.status == "scheduled":
                            if st.button("✅ Complete", key=f"complete_{appt.id}"):
                                appt_repo.update_status(appt.id, "completed")
                                st.rerun()
                    with col3:
                        if appt.status == "scheduled":
                            if st.button("❌ Cancel", key=f"cancel_{appt.id}"):
                                appt_repo.update_status(appt.id, "cancelled")
                                # Notify patient
                                msg_repo.send(
                                    sender_id=user["id"],
                                    receiver_id=appt.patient_id,
                                    subject=f"❌ Appointment Cancelled — {format_date(appt.appointment_date)}",
                                    body=(
                                        f"Dear {appt.patient_name},\n\n"
                                        f"Your appointment on {format_date(appt.appointment_date)} "
                                        f"at {format_time(appt.appointment_time)} has been cancelled.\n\n"
                                        f"Please contact us to reschedule.\n\n"
                                        f"— Dr. {user['full_name']}"
                                    ),
                                )
                                st.rerun()

                    # Doctor notes
                    with st.expander("📝 Add/View Doctor Notes"):
                        note_val = appt.doctor_notes or ""
                        new_note = st.text_area("Doctor Notes", value=note_val, key=f"note_{appt.id}")
                        if st.button("Save Notes", key=f"save_note_{appt.id}"):
                            appt_repo.update_notes(appt.id, doctor_notes=new_note)
                            st.success("Notes saved!")

    # ── TAB 3: History ───────────────────────────────────────────
    with history_tab:
        st.subheader("🗂️ Appointment History")
        all_appts = appt_repo.get_for_doctor(user["id"], upcoming_only=False)
        past = [a for a in all_appts if a.appointment_date < date.today() or a.status in ("completed", "cancelled")]

        if not past:
            st.info("No past appointments yet.")
        else:
            st.dataframe([{
                "Patient":    a.patient_name,
                "Date":       format_date(a.appointment_date),
                "Time":       format_time(a.appointment_time),
                "Location":   a.location,
                "Severity":   a.severity_level,
                "Status":     a.status.title(),
                "Reason":     (a.reason or "")[:60],
            } for a in past], width="stretch")


# ================================================================
# PATIENT VIEW
# ================================================================
elif role == "patient":
    upcoming_tab, history_tab = st.tabs(["📅 My Appointments", "🗂️ Past Appointments"])

    # ── TAB 1: Upcoming ──────────────────────────────────────────
    with upcoming_tab:
        st.subheader("📅 Your Upcoming Appointments")
        upcoming_appts = appt_repo.get_for_patient(user["id"], upcoming_only=True)

        if not upcoming_appts:
            st.info("You have no upcoming appointments. Your doctor will book one if needed.")
        else:
            for appt in upcoming_appts:
                sev_icon = _SEVERITY_ICONS.get(appt.severity_level, "🔵")
                days_left = (appt.appointment_date - date.today()).days

                # Urgency banner
                if days_left == 0:
                    st.error(f"🚨 You have an appointment **TODAY**!")
                elif days_left == 1:
                    st.warning(f"⏰ Appointment **TOMORROW**!")
                elif days_left <= 3:
                    st.warning(f"📅 Appointment in {days_left} days")

                with st.container(border=True):
                    # Big clear appointment card
                    st.markdown(f"""
                    <div style="background: #E7F4EF; border-radius: 12px; padding: 20px; border-left: 5px solid #0E7A5C;">
                        <h3 style="color: #0E7A5C; margin: 0 0 12px 0;">📅 Appointment with Dr. {appt.doctor_name}</h3>
                        <table style="width: 100%; font-size: 15px;">
                            <tr>
                                <td style="padding: 6px 0;"><strong>📆 Date:</strong></td>
                                <td style="color: #16242B; font-weight: 600;">{format_date(appt.appointment_date)}</td>
                            </tr>
                            <tr>
                                <td style="padding: 6px 0;"><strong>⏰ Time:</strong></td>
                                <td style="color: #16242B; font-weight: 600;">{format_time(appt.appointment_time)}</td>
                            </tr>
                            <tr>
                                <td style="padding: 6px 0;"><strong>📍 Location:</strong></td>
                                <td style="color: #16242B;">{appt.location}</td>
                            </tr>
                            <tr>
                                <td style="padding: 6px 0;"><strong>{sev_icon} Urgency:</strong></td>
                                <td style="color: #16242B;">{appt.severity_level.title()}</td>
                            </tr>
                        </table>
                    </div>
                    """, unsafe_allow_html=True)

                    if appt.reason:
                        st.info(f"📋 **Doctor's Note:** {appt.reason}")

                    if appt.doctor_notes:
                        st.info(f"📝 **Additional Notes:** {appt.doctor_notes}")

                    # Days countdown
                    if days_left > 0:
                        st.success(f"⏳ **{days_left} day(s) remaining** until your appointment")
                    elif days_left == 0:
                        st.error("🚨 **This appointment is TODAY!**")

                    # Patient notes
                    with st.expander("📝 Add Your Notes / Confirm Attendance"):
                        patient_note = st.text_area(
                            "Your Notes",
                            value=appt.patient_notes or "",
                            placeholder="e.g. I will attend. I have questions about my medication.",
                            key=f"p_note_{appt.id}"
                        )
                        col1, col2 = st.columns(2)
                        with col1:
                            if st.button("💾 Save Notes", key=f"save_p_{appt.id}"):
                                appt_repo.update_notes(appt.id, patient_notes=patient_note)
                                st.success("Notes saved!")
                        with col2:
                            if st.button("✅ Confirm Attendance", key=f"confirm_{appt.id}"):
                                msg_repo.send(
                                    sender_id=user["id"],
                                    receiver_id=appt.doctor_id,
                                    subject=f"✅ Appointment Confirmed — {user['full_name']}",
                                    body=(
                                        f"Dear Dr. {appt.doctor_name},\n\n"
                                        f"I confirm I will attend my appointment on "
                                        f"{format_date(appt.appointment_date)} at "
                                        f"{format_time(appt.appointment_time)}.\n\n"
                                        f"— {user['full_name']}"
                                    ),
                                )
                                st.success("✅ Confirmation sent to your doctor!")

                    # Print / Share buttons
                    st.markdown("<br>", unsafe_allow_html=True)
                    pcol1, pcol2, pcol3 = st.columns(3)
                    with pcol1:
                        appt_text = generate_appointment_text(appt, user["full_name"])
                        st.download_button(
                            "🖨️ Print Appointment",
                            data=appt_text,
                            file_name=f"appointment_{appt.appointment_date}_{user['full_name'].replace(' ','_')}.txt",
                            mime="text/plain",
                            key=f"print_{appt.id}",
                            width="stretch",
                        )
                    with pcol2:
                        appt_html = generate_appointment_html(appt, user["full_name"])
                        st.download_button(
                            "📤 Download (HTML)",
                            data=appt_html,
                            file_name=f"appointment_{appt.appointment_date}_{user['full_name'].replace(' ','_')}.html",
                            mime="text/html",
                            key=f"html_{appt.id}",
                            width="stretch",
                        )
                    with pcol3:
                        share_text = (
                            f"📅 Appointment with Dr. {appt.doctor_name}\n"
                            f"📆 {format_date(appt.appointment_date)}\n"
                            f"⏰ {format_time(appt.appointment_time)}\n"
                            f"📍 {appt.location}\n"
                            f"📋 {appt.severity_level.title()}"
                        )
                        st.code(share_text, language=None, key=f"share_{appt.id}")
                        st.caption("📋 Copy the text above to share")

    # ── TAB 2: History ───────────────────────────────────────────
    with history_tab:
        st.subheader("🗂️ Past Appointments")
        all_appts = appt_repo.get_for_patient(user["id"], upcoming_only=False)
        past = [a for a in all_appts if a.appointment_date < date.today() or a.status in ("completed", "cancelled")]

        if not past:
            st.info("No past appointments yet.")
        else:
            for appt in past:
                status_icon, bg = _STATUS_COLORS.get(appt.status, ("🔵", "#EFF3F1"))
                with st.container(border=True):
                    st.markdown(f"{status_icon} **{format_date(appt.appointment_date)}** at {format_time(appt.appointment_time)} — Dr. {appt.doctor_name}")
                    st.caption(f"📍 {appt.location} | Status: {appt.status.title()}")
                    if appt.reason:
                        st.caption(f"Reason: {appt.reason}")
                    if appt.doctor_notes:
                        st.info(f"📝 Doctor's Notes: {appt.doctor_notes}")

                    pcol1, pcol2 = st.columns(2)
                    with pcol1:
                        appt_text = generate_appointment_text(appt, user["full_name"])
                        st.download_button(
                            "🖨️ Print",
                            data=appt_text,
                            file_name=f"appointment_{appt.appointment_date}_{user['full_name'].replace(' ','_')}.txt",
                            mime="text/plain",
                            key=f"print_past_{appt.id}",
                            width="stretch",
                        )
                    with pcol2:
                        appt_html = generate_appointment_html(appt, user["full_name"])
                        st.download_button(
                            "📤 Download HTML",
                            data=appt_html,
                            file_name=f"appointment_{appt.appointment_date}_{user['full_name'].replace(' ','_')}.html",
                            mime="text/html",
                            key=f"html_past_{appt.id}",
                            width="stretch",
                        )


else:
    st.error("Access denied.")

if st.button("Log Out"):
    SessionManager.logout()
    st.rerun()
