"""
8_Medications.py
-----------------
Medication Tracking + BMI & Lifestyle Data page for patients.

Features:
  - Add, view, stop medications
  - Log daily medication intake (taken / missed)
  - Adherence rate tracker
  - BMI calculator with history
  - Lifestyle data form (smoking, cholesterol, exercise)
  - Lifestyle data feeds back into ML model predictions
"""

import streamlit as st
from datetime import date, datetime
from io import BytesIO
from app.core.security import SessionManager
from app.database.repositories.medication_repository import MedicationRepository
from app.database.repositories.lifestyle_repository import LifestyleRepository
from app.services.medication_interaction_service import MedicationInteractionService
from app.utils.custom_css import apply_theme, profile_widget, notification_bell, page_header

st.set_page_config(page_title="Medications & Lifestyle", page_icon=":material/medication:", layout="wide")
apply_theme()

user = SessionManager.get_current_user()
if not user:
    st.warning("Please log in first.")
    st.stop()

if user["role"] not in ("patient", "doctor"):
    st.error("Access denied.")
    st.stop()

med_repo       = MedicationRepository()
lifestyle_repo = LifestyleRepository()
interaction_svc = MedicationInteractionService()

profile_widget(user)
notification_bell(user)

st.markdown(page_header(":material/medication:", "Medications & Lifestyle", "Prescriptions, adherence, and lifestyle habits at a glance"), unsafe_allow_html=True)


def generate_medication_pdf(patient_name: str, active_meds, stopped_meds, adherence_rate: float) -> bytes:
    from fpdf import FPDF

    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # Header
    pdf.set_fill_color(34, 169, 150)
    pdf.rect(0, 0, 210, 35, "F")
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_y(8)
    pdf.cell(0, 10, "Remote Patient Monitoring System", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 8, "Medication Report", align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.set_y(42)
    pdf.set_text_color(0, 0, 0)

    # Patient info
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, f"Patient: {patient_name}", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 6, f"Generated: {datetime.now().strftime('%d %B %Y, %H:%M')}", new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(4)

    # Adherence
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 8, f"30-Day Adherence Rate: {adherence_rate}%", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    # Active medications
    pdf.set_draw_color(34, 169, 150)
    pdf.set_line_width(0.5)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(4)
    pdf.set_font("Helvetica", "B", 13)
    pdf.cell(0, 8, f"Active Medications ({len(active_meds)})", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    if active_meds:
        for med in active_meds:
            pdf.set_font("Helvetica", "B", 11)
            pdf.cell(0, 7, med.name, new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(80, 80, 80)
            pdf.cell(0, 6, f"Dosage: {med.dosage}  |  Frequency: {med.frequency}  |  Route: {med.route}", new_x="LMARGIN", new_y="NEXT")
            pdf.cell(0, 6, f"Start Date: {med.start_date}" + (f"  |  Prescribed by: {med.prescribed_by}" if med.prescribed_by else ""), new_x="LMARGIN", new_y="NEXT")
            if med.notes:
                pdf.cell(0, 6, f"Notes: {med.notes}", new_x="LMARGIN", new_y="NEXT")
            pdf.set_text_color(0, 0, 0)
            pdf.ln(3)
    else:
        pdf.set_font("Helvetica", "I", 10)
        pdf.cell(0, 7, "No active medications.", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

    # Stopped medications
    if stopped_meds:
        pdf.ln(2)
        pdf.set_draw_color(34, 169, 150)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(4)
        pdf.set_font("Helvetica", "B", 13)
        pdf.cell(0, 8, f"Past Medications ({len(stopped_meds)})", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)
        for med in stopped_meds:
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(120, 120, 120)
            pdf.cell(0, 6, f"{med.name} - {med.dosage} ({med.frequency}) | Stopped: {med.end_date or 'Unknown'}", new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(0, 0, 0)

    # Footer
    pdf.ln(10)
    pdf.set_draw_color(34, 169, 150)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(4)
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 6, "Generated by RPM System", align="C", new_x="LMARGIN", new_y="NEXT")

    return bytes(pdf.output())

# ================================================================
# DOCTOR VIEW
# ================================================================
if user["role"] == "doctor":
    st.caption("Prescribe and manage medications for your patients.")

    from app.services.doctor_service import DoctorService
    doctor_service = DoctorService()
    patients = doctor_service.get_assigned_patients(user["id"])
    patient_map = {
        (p.full_name or f"Patient #{p.user_id}"): p.user_id
        for p in patients
    }

    if not patients:
        st.info("No patients assigned to you yet.")
    else:
        selected_patient_name = st.selectbox("Select Patient", list(patient_map.keys()))
        patient_id = patient_map[selected_patient_name]

        prescribe_tab, view_tab = st.tabs(["Prescribe medication", "View patient medications"])

        # ── TAB 1: Prescribe ──────────────────────────────────────
        with prescribe_tab:
            st.subheader(f"Prescribe medication for {selected_patient_name}")

            with st.form("prescribe_med_form", clear_on_submit=True):
                c1, c2 = st.columns(2)
                with c1:
                    med_name = st.text_input("Medication Name",
                                              placeholder="e.g. Metformin, Lisinopril")
                    dosage = st.text_input("Dosage",
                                            placeholder="e.g. 500mg, 10mg")
                    frequency = st.selectbox("Frequency", [
                        "Once daily", "Twice daily", "Three times daily",
                        "Four times daily", "Every morning", "Every night",
                        "Every 8 hours", "Every 12 hours", "Weekly", "As needed"
                    ])
                with c2:
                    route = st.selectbox("Route", [
                        "oral", "injection", "topical", "inhaled",
                        "sublingual", "intravenous", "other"
                    ])
                    start_date = st.date_input("Start Date", value=date.today())

                med_notes = st.text_area("Prescription Notes (optional)",
                                          placeholder="e.g. Take with food. Monitor blood sugar after 2 weeks.")

                if st.form_submit_button("Prescribe medication", width="stretch"):
                    if not med_name or not dosage:
                        st.error("Please fill in medication name and dosage.")
                    else:
                        med_repo.add(
                            patient_id=patient_id,
                            name=med_name.strip(), dosage=dosage.strip(),
                            frequency=frequency, route=route,
                            start_date=start_date,
                            prescribed_by=user["full_name"],
                            notes=med_notes or None,
                        )
                        st.success(f"{med_name} prescribed to {selected_patient_name} successfully!")
                        st.rerun()

        # ── TAB 2: View Patient Medications ───────────────────────
        with view_tab:
            st.subheader(f"Medications for {selected_patient_name}")

            active_meds = med_repo.list_for_patient(patient_id, active_only=True)
            if not active_meds:
                st.info("No active medications for this patient.")
            else:
                st.markdown("#### Active Medications")
                for med in active_meds:
                    with st.container(border=True):
                        c1, c2 = st.columns([5, 1])
                        with c1:
                            st.markdown(f"""
                            <div style="display:flex;align-items:center;gap:12px;">
                                <div class="material-symbols-outlined" style="width:40px;height:40px;border-radius:50%;
                                     background:#0E7A5C;color:white;display:flex;
                                     align-items:center;justify-content:center;
                                     font-size:18px;">medication</div>
                                <div>
                                    <strong style="font-size:15px;">{med.name}</strong>
                                    <br>
                                    <span style="color:#5F717A;font-size:13px;">
                                        {med.dosage} — {med.frequency} — {med.route}
                                    </span>
                                    <br>
                                    <span style="color:#5F717A;font-size:12px;">
                                        Started: {med.start_date}
                                        {f" | Prescribed by: {med.prescribed_by}" if med.prescribed_by else ""}
                                    </span>
                                </div>
                            </div>
                            """, unsafe_allow_html=True)
                            if med.notes:
                                st.caption(f":material/edit_note: {med.notes}")
                        with c2:
                            if st.button("⏹ Stop", key=f"doc_stop_{med.id}"):
                                med_repo.stop(med.id, patient_id)
                                st.success(f"{med.name} stopped.")
                                st.rerun()

            # Stopped/past medications
            all_meds = med_repo.list_for_patient(patient_id, active_only=False)
            stopped = [m for m in all_meds if not m.is_active]
            if stopped:
                with st.expander(f"Past medications ({len(stopped)})"):
                    for med in stopped:
                        st.markdown(f"~~{med.name}~~ — {med.dosage} "
                                    f"({med.frequency}) | Stopped: {med.end_date or 'Unknown'}")

            # Adherence rate
            if active_meds:
                rate = med_repo.get_adherence_rate(patient_id, days=30)
                color = "#0E7A5C" if rate >= 80 else "#B8761D" if rate >= 50 else "#C73E3A"
                st.markdown(f"""
                <div style="background:white;border:1px solid #DCE5E1;border-radius:10px;
                     padding:16px;display:flex;align-items:center;justify-content:space-between;">
                    <div>
                        <div style="font-size:11px;font-weight:600;text-transform:uppercase;
                             color:#5F717A;letter-spacing:.03em;">30-Day Adherence Rate</div>
                        <div style="font-size:11px;color:#5F717A;margin-top:2px;">
                            Based on daily medication logs
                        </div>
                    </div>
                    <div style="font-size:32px;font-weight:800;color:{color};font-family:monospace;">
                        {rate}%
                    </div>
                </div>
                """, unsafe_allow_html=True)

                # Interaction warnings
                active_med_names = [m.name for m in active_meds]
                interactions = interaction_svc.check_interactions(active_med_names)
                if interactions:
                    st.subheader("Drug interaction warnings")
                    for interaction in interactions:
                        severity_color = "#C73E3A" if interaction["severity"] == "severe" else "#B8761D"
                        st.markdown(f"""
                        <div style="background:#FBF3E4;border:1px solid {severity_color};border-radius:8px;
                             padding:12px 16px;margin-bottom:8px;">
                            <div style="font-weight:600;color:{severity_color};">
                                {interaction['severity'].upper()} Interaction
                            </div>
                            <div style="font-size:13px;margin-top:4px;">
                                <strong>{interaction['drug_a']}</strong> + <strong>{interaction['drug_b']}</strong>
                            </div>
                            <div style="font-size:12px;color:#5F717A;margin-top:4px;">
                                {interaction['description']}
                            </div>
                        </div>
                        """, unsafe_allow_html=True)


# ================================================================
# PATIENT VIEW
# ================================================================
elif user["role"] == "patient":
    st.caption("Track your medications, BMI, and lifestyle data to improve AI prediction accuracy.")

    med_tab, log_tab, lifestyle_tab, bmi_tab = st.tabs([
        "My medications", "Daily log", "Lifestyle and BMI", "BMI history"
    ])

    patient_id = user["id"]

    # ── TAB 1: Medications ────────────────────────────────────────
    with med_tab:
        st.subheader("My Current Medications")

        with st.expander("Add new medication", expanded=False):
            with st.form("add_med_form", clear_on_submit=True):
                c1, c2 = st.columns(2)
                with c1:
                    med_name = st.text_input("Medication Name",
                                              placeholder="e.g. Metformin, Lisinopril")
                    dosage = st.text_input("Dosage",
                                            placeholder="e.g. 500mg, 10mg")
                    frequency = st.selectbox("Frequency", [
                        "Once daily", "Twice daily", "Three times daily",
                        "Four times daily", "Every morning", "Every night",
                        "Every 8 hours", "Every 12 hours", "Weekly", "As needed"
                    ])
                with c2:
                    route = st.selectbox("Route", [
                        "oral", "injection", "topical", "inhaled",
                        "sublingual", "intravenous", "other"
                    ])
                    start_date = st.date_input("Start Date", value=date.today())
                    prescribed_by = st.text_input("Prescribed By",
                                                   placeholder="e.g. Dr. Kwame Mensah")

                med_notes = st.text_area("Notes (optional)",
                                          placeholder="e.g. Take with food, avoid grapefruit")

                if st.form_submit_button("Add medication", width="stretch"):
                    if not med_name or not dosage:
                        st.error("Please fill in medication name and dosage.")
                    else:
                        med_repo.add(
                            patient_id=patient_id,
                            name=med_name.strip(), dosage=dosage.strip(),
                            frequency=frequency, route=route,
                            start_date=start_date,
                            prescribed_by=prescribed_by or None,
                            notes=med_notes or None,
                        )
                        st.success(f"{med_name} added successfully!")
                        st.rerun()

        st.markdown("#### Active Medications")
        active_meds = med_repo.list_for_patient(patient_id, active_only=True)

        if not active_meds:
            st.info("No active medications recorded. Add one above.")
        else:
            for med in active_meds:
                with st.container(border=True):
                    c1, c2, c3 = st.columns([5, 1, 1])
                    with c1:
                        st.markdown(f"""
                        <div style="display:flex;align-items:center;gap:12px;">
                            <div class="material-symbols-outlined" style="width:40px;height:40px;border-radius:50%;
                                 background:#0E7A5C;color:white;display:flex;
                                 align-items:center;justify-content:center;
                                 font-size:18px;">medication</div>
                            <div>
                                <strong style="font-size:15px;">{med.name}</strong>
                                <br>
                                <span style="color:#5F717A;font-size:13px;">
                                    {med.dosage} — {med.frequency} — {med.route}
                                </span>
                                <br>
                                <span style="color:#5F717A;font-size:12px;">
                                    Started: {med.start_date}
                                    {f" | Prescribed by: {med.prescribed_by}" if med.prescribed_by else ""}
                                </span>
                            </div>
                        </div>
                        """, unsafe_allow_html=True)
                        if med.notes:
                            st.caption(f":material/edit_note: {med.notes}")
                    with c2:
                        if st.button("⏹ Stop", key=f"stop_{med.id}",
                                      help="Mark this medication as stopped"):
                            med_repo.stop(med.id, patient_id)
                            st.success(f"{med.name} stopped.")
                            st.rerun()
                    with c3:
                        if st.button(":material/delete:", key=f"del_{med.id}", help="Delete"):
                            if st.session_state.get(f"confirm_del_{med.id}"):
                                med_repo.delete(med.id, patient_id)
                                st.rerun()
                            else:
                                st.session_state[f"confirm_del_{med.id}"] = True

        all_meds = med_repo.list_for_patient(patient_id, active_only=False)
        stopped = [m for m in all_meds if not m.is_active]
        if stopped:
            with st.expander(f"Past medications ({len(stopped)})"):
                for med in stopped:
                    st.markdown(f"~~{med.name}~~ — {med.dosage} "
                                f"({med.frequency}) | Stopped: {med.end_date or 'Unknown'}")

        # PDF download
        all_meds_full = med_repo.list_for_patient(patient_id, active_only=False)
        active_all = [m for m in all_meds_full if m.is_active]
        stopped_all = [m for m in all_meds_full if not m.is_active]
        adherence = med_repo.get_adherence_rate(patient_id, days=30) if active_all else 0.0
        pdf_bytes = generate_medication_pdf(user["full_name"], active_all, stopped_all, adherence)
        st.download_button(
            "Download medications as PDF",
            data=pdf_bytes,
            file_name=f"medications_{user['full_name'].replace(' ', '_')}_{date.today()}.pdf",
            mime="application/pdf",
            width="stretch",
        )

        if active_meds:
            rate = med_repo.get_adherence_rate(patient_id, days=30)
            color = "#0E7A5C" if rate >= 80 else "#B8761D" if rate >= 50 else "#C73E3A"
            st.markdown(f"""
            <div style="background:white;border:1px solid #DCE5E1;border-radius:10px;
                 padding:16px;display:flex;align-items:center;justify-content:space-between;">
                <div>
                    <div style="font-size:11px;font-weight:600;text-transform:uppercase;
                         color:#5F717A;letter-spacing:.03em;">30-Day Adherence Rate</div>
                    <div style="font-size:11px;color:#5F717A;margin-top:2px;">
                        Based on your daily medication logs
                    </div>
                </div>
                <div style="font-size:32px;font-weight:800;color:{color};font-family:monospace;">
                    {rate}%
                </div>
            </div>
            """, unsafe_allow_html=True)

            active_med_names = [m.name for m in active_meds]
            interactions = interaction_svc.check_interactions(active_med_names)
            if interactions:
                st.subheader("Drug interaction warnings")
                for interaction in interactions:
                    severity_color = "#C73E3A" if interaction["severity"] == "severe" else "#B8761D"
                    st.markdown(f"""
                    <div style="background:#FBF3E4;border:1px solid {severity_color};border-radius:8px;
                         padding:12px 16px;margin-bottom:8px;">
                        <div style="font-weight:600;color:{severity_color};">
                            {interaction['severity'].upper()} Interaction
                        </div>
                        <div style="font-size:13px;margin-top:4px;">
                            <strong>{interaction['drug_a']}</strong> + <strong>{interaction['drug_b']}</strong>
                        </div>
                        <div style="font-size:12px;color:#5F717A;margin-top:4px;">
                            {interaction['description']}
                        </div>
                    </div>
                    """, unsafe_allow_html=True)

    # ── TAB 2: Daily Medication Log ───────────────────────────────
    with log_tab:
        st.subheader("Daily medication log")
        st.caption(f"Today: {date.today().strftime('%A, %d %B %Y')}")

        active_meds = med_repo.list_for_patient(patient_id, active_only=True)
        today_logs  = med_repo.get_today_logs(patient_id)
        logged_ids  = {log.medication_id for log in today_logs}

        if not active_meds:
            st.info("No active medications to log. Add medications in the 'My Medications' tab.")
        else:
            st.markdown("Mark each medication as taken or missed for today:")
            st.markdown("<br>", unsafe_allow_html=True)

            for med in active_meds:
                already_logged = med.id in logged_ids
                log_for_today  = next((l for l in today_logs if l.medication_id == med.id), None)

                with st.container(border=True):
                    c1, c2, c3 = st.columns([4, 1, 1])
                    with c1:
                        status_icon = ":material/check_circle:" if (already_logged and log_for_today and log_for_today.taken) else \
                                      ":material/cancel:" if (already_logged and log_for_today and not log_for_today.taken) else ":material/schedule:"
                        st.markdown(f"""
                        <strong>{status_icon} {med.name}</strong>
                        <span style="color:#5F717A;font-size:13px;">
                            — {med.dosage} ({med.frequency})
                        </span>
                        """, unsafe_allow_html=True)
                        if already_logged:
                            taken_text = "Taken :material/check_circle:" if log_for_today.taken else "Missed :material/cancel:"
                            st.caption(f"Already logged today: {taken_text}")

                    if not already_logged:
                        with c2:
                            if st.button(":material/check_circle: Taken", key=f"taken_{med.id}",
                                          width="stretch"):
                                med_repo.log_taken(med.id, patient_id, taken=True)
                                st.success(f"Logged: {med.name} taken")
                                st.rerun()
                        with c3:
                            if st.button(":material/cancel: Missed", key=f"missed_{med.id}",
                                          width="stretch"):
                                med_repo.log_taken(med.id, patient_id, taken=False)
                                st.warning(f"Logged: {med.name} missed")
                                st.rerun()

            if today_logs:
                taken_count  = sum(1 for l in today_logs if l.taken)
                missed_count = sum(1 for l in today_logs if not l.taken)
                m1, m2, m3 = st.columns(3)
                m1.metric("Total Medications", len(active_meds))
                m2.metric("Taken today",    taken_count)
                m3.metric("Missed today",   missed_count)

    # ── TAB 3: Lifestyle & BMI ────────────────────────────────────
    with lifestyle_tab:
        st.subheader("Lifestyle and BMI data")
        st.info("This data improves the accuracy of your AI risk predictions. "
                "Please update whenever your lifestyle changes.")

        latest = lifestyle_repo.get_latest(patient_id)
        if latest:
            st.markdown("#### Your Latest Lifestyle Record")
            c1, c2, c3, c4 = st.columns(4)
            c1.metric("BMI",        f"{float(latest.bmi):.1f}" if latest.bmi else "—")
            c2.metric("Cholesterol",f"{float(latest.total_cholesterol):.0f} mg/dL"
                                    if latest.total_cholesterol else "—")
            c3.metric("Exercise",   f"{latest.exercise_minutes_week or 0} min/week")
            c4.metric("Smoking",    latest.smoking_status or "—")
            st.caption(f"Last updated: {latest.recorded_at}")

        with st.form("lifestyle_form", clear_on_submit=True):
            st.markdown("#### Body measurements")
            c1, c2 = st.columns(2)
            with c1:
                height_cm = st.number_input("Height (cm)", min_value=0.0,
                                             max_value=250.0, value=0.0, step=0.5,
                                             help="Used to calculate BMI")
            with c2:
                weight_kg = st.number_input("Weight (kg)", min_value=0.0,
                                             max_value=300.0, value=0.0, step=0.1)

            if height_cm > 0 and weight_kg > 0:
                bmi_val = weight_kg / ((height_cm / 100) ** 2)
                bmi_cat = ("Underweight" if bmi_val < 18.5 else
                           "Normal weight" if bmi_val < 25 else
                           "Overweight" if bmi_val < 30 else "Obese")
                bmi_color = ("#0E7A5C" if bmi_val < 25 else
                             "#B8761D" if bmi_val < 30 else "#C73E3A")
                st.markdown(f"""
                <div style="background:#E7F4EF;border:1px solid #E7F4EF;
                     border-radius:8px;padding:10px 14px;margin:8px 0;">
                    Calculated BMI: <strong style="color:{bmi_color};
                    font-size:18px;">{bmi_val:.1f}</strong>
                    <span style="color:#5F717A;"> — {bmi_cat}</span>
                </div>
                """, unsafe_allow_html=True)

            st.markdown("#### Smoking and alcohol")
            c1, c2 = st.columns(2)
            with c1:
                smoking_status = st.selectbox("Smoking Status", [
                    "never smoked", "formerly smoked", "smokes", "unknown"
                ])
                cigarettes = st.number_input("Cigarettes per day (if smoker)",
                                              min_value=0, max_value=100, value=0)
            with c2:
                alcohol = st.number_input("Alcohol units per week",
                                           min_value=0, max_value=100, value=0,
                                           help="1 unit = 1 small beer or 1 shot of spirits")

            st.markdown("#### Cholesterol levels")
            c1, c2, c3 = st.columns(3)
            with c1:
                total_chol = st.number_input("Total Cholesterol (mg/dL)",
                                              min_value=0.0, max_value=500.0, value=0.0,
                                              help="Normal: below 200 mg/dL")
            with c2:
                hdl_chol = st.number_input("HDL Cholesterol (mg/dL)",
                                            min_value=0.0, max_value=200.0, value=0.0,
                                            help="Good cholesterol — higher is better")
            with c3:
                ldl_chol = st.number_input("LDL Cholesterol (mg/dL)",
                                            min_value=0.0, max_value=400.0, value=0.0,
                                            help="Bad cholesterol — lower is better")

            st.markdown("#### Physical activity")
            c1, c2 = st.columns(2)
            with c1:
                exercise_mins = st.number_input("Exercise (minutes per week)",
                                                 min_value=0, max_value=3000, value=0)
            with c2:
                activity_level = st.selectbox("Overall Activity Level", [
                    "sedentary", "light", "moderate", "active", "very active"
                ])

            diet_type = st.text_input("Diet Type (optional)",
                                       placeholder="e.g. low-sugar, low-salt, balanced, vegetarian")
            lifestyle_notes = st.text_area("Additional Notes (optional)")

            if st.form_submit_button("Save lifestyle data", width="stretch"):
                lifestyle_repo.save(
                    patient_id=patient_id,
                    height_cm=height_cm if height_cm > 0 else None,
                    weight_kg=weight_kg if weight_kg > 0 else None,
                    smoking_status=smoking_status,
                    cigarettes_per_day=cigarettes if cigarettes > 0 else None,
                    alcohol_units_week=alcohol if alcohol > 0 else None,
                    total_cholesterol=total_chol if total_chol > 0 else None,
                    hdl_cholesterol=hdl_chol if hdl_chol > 0 else None,
                    ldl_cholesterol=ldl_chol if ldl_chol > 0 else None,
                    exercise_minutes_week=exercise_mins if exercise_mins > 0 else None,
                    activity_level=activity_level,
                    diet_type=diet_type or None,
                    notes=lifestyle_notes or None,
                )
                st.success("Lifestyle data saved! This will improve your AI risk predictions.")
                st.balloons()
                st.rerun()

    # ── TAB 4: BMI History ────────────────────────────────────────
    with bmi_tab:
        st.subheader("BMI and lifestyle history")
        history = lifestyle_repo.get_history(patient_id, limit=20)

        if not history:
            st.info("No lifestyle records yet. Add your first record in the 'Lifestyle & BMI' tab.")
        else:
            import plotly.graph_objects as go
            bmi_records = [r for r in history if r.bmi]
            if bmi_records:
                fig = go.Figure()
                fig.add_trace(go.Scatter(
                    x=[r.recorded_at for r in reversed(bmi_records)],
                    y=[float(r.bmi) for r in reversed(bmi_records)],
                    mode="lines+markers",
                    line=dict(color="#0E7A5C", width=2),
                    marker=dict(size=8),
                    name="BMI",
                ))
                fig.add_hrect(y0=0,     y1=18.5, fillcolor="lightblue",   opacity=0.1, annotation_text="Underweight")
                fig.add_hrect(y0=18.5,  y1=25,   fillcolor="lightgreen",  opacity=0.1, annotation_text="Normal")
                fig.add_hrect(y0=25,    y1=30,   fillcolor="lightyellow", opacity=0.1, annotation_text="Overweight")
                fig.add_hrect(y0=30,    y1=50,   fillcolor="lightsalmon", opacity=0.1, annotation_text="Obese")
                fig.update_layout(
                    title="BMI Over Time",
                    xaxis_title="Date",
                    yaxis_title="BMI",
                    yaxis=dict(range=[10, 50]),
                    margin=dict(t=60),
                )
                st.plotly_chart(fig, width="stretch")

            st.markdown("#### Lifestyle Records")
            st.dataframe([{
                "Date":           r.recorded_at,
                "Height (cm)":    float(r.height_cm) if r.height_cm else "—",
                "Weight (kg)":    float(r.weight_kg) if r.weight_kg else "—",
                "BMI":            float(r.bmi) if r.bmi else "—",
                "Smoking":        r.smoking_status or "—",
                "Cholesterol":    float(r.total_cholesterol) if r.total_cholesterol else "—",
                "Exercise (min)": r.exercise_minutes_week or "—",
                "Activity":       r.activity_level or "—",
            } for r in history], width="stretch")

if st.button("Log Out"):
    SessionManager.logout()
    st.rerun()
