-- ==============================================================
-- Seed Data — FOR DEVELOPMENT/DEMO PURPOSES ONLY
-- ==============================================================
-- Run AFTER schema.sql:
--   mysql -u root -p rpm_system < database/seed_data.sql
--
-- NOTE: password_hash values below are placeholders. Real bcrypt
-- hashes will be generated by the auth_service in Phase 4 —
-- do not treat these as valid login credentials yet.
-- ==============================================================

USE rpm_system;

-- --- Admin ---
INSERT INTO users (full_name, email, password_hash, role) VALUES
('System Administrator', 'admin@rpm-system.local', 'PLACEHOLDER_HASH', 'admin');

-- --- Doctors ---
INSERT INTO users (full_name, email, password_hash, role) VALUES
('Dr. Ama Owusu', 'ama.owusu@rpm-system.local', 'PLACEHOLDER_HASH', 'doctor'),
('Dr. Kwame Boateng', 'kwame.boateng@rpm-system.local', 'PLACEHOLDER_HASH', 'doctor');

INSERT INTO doctors (user_id, specialization, license_number) VALUES
((SELECT id FROM users WHERE email = 'ama.owusu@rpm-system.local'), 'Neurology', 'LIC-1001'),
((SELECT id FROM users WHERE email = 'kwame.boateng@rpm-system.local'), 'Endocrinology', 'LIC-1002');

-- --- Patients ---
INSERT INTO users (full_name, email, password_hash, role) VALUES
('John Mensah', 'john.mensah@example.com', 'PLACEHOLDER_HASH', 'patient'),
('Grace Adjei', 'grace.adjei@example.com', 'PLACEHOLDER_HASH', 'patient');

INSERT INTO patients (user_id, date_of_birth, gender, assigned_doctor_id, chronic_conditions) VALUES
(
    (SELECT id FROM users WHERE email = 'john.mensah@example.com'),
    '1968-03-14', 'male',
    (SELECT user_id FROM doctors WHERE license_number = 'LIC-1001'),
    'stroke,hypertension'
),
(
    (SELECT id FROM users WHERE email = 'grace.adjei@example.com'),
    '1975-11-02', 'female',
    (SELECT user_id FROM doctors WHERE license_number = 'LIC-1002'),
    'diabetes'
);

-- --- Sample vitals for John Mensah ---
INSERT INTO vitals_records (patient_id, systolic_bp, diastolic_bp, heart_rate, glucose_level, weight_kg, oxygen_saturation, symptoms)
VALUES
(
    (SELECT id FROM users WHERE email = 'john.mensah@example.com'),
    168, 102, 88, 110.5, 82.3, 96, 'Mild headache, slight dizziness'
);

-- --- Sample vitals for Grace Adjei ---
INSERT INTO vitals_records (patient_id, systolic_bp, diastolic_bp, heart_rate, glucose_level, weight_kg, oxygen_saturation, symptoms)
VALUES
(
    (SELECT id FROM users WHERE email = 'grace.adjei@example.com'),
    122, 78, 74, 185.0, 68.0, 98, 'Increased thirst, fatigue'
);
